### ISSUE TITLE
.cookiecutter.json is not being found

### ISSUE THREAD

**Issue by mario-bermonti** [cjolowicz/retrocookie#582]
I have a project based on a cookiecutter template. I followed retrocookie's docs but I get the error below when I run 
`poetry run retrocookie ../wdiff/ aa3a185 --create-branch=separate-security-checks` in the root of the cookiecutter repo.

I do have a `.cookiecutter.json` in the root of the project created from the template. This file was created by the file `.cookiecutter.json` with the contents `{{ cookiecutter | jsonify }}` on the template's directory, as recommended in the docs.

Am I doing something wrong?

P.D. Seems like a great project.

```
Traceback (most recent call last):
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/bin/retrocookie", line 8, in <module>
    sys.exit(main())
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/retrocookie/__main__.py", line 120, in main
    retrocookie(
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/retrocookie/core.py", line 162, in retrocookie
    commits = rewrite_commits(
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/retrocookie/core.py", line 77, in rewrite_commits
    context = load_context(source, commits[-1])
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/retrocookie/core.py", line 39, in load_context
    text = repository.read_text(path, ref=ref)
  File "/Users/MBP/programming_projects/cookiecutter-modern-pypackage/.venv/lib/python3.9/site-packages/retrocookie/git.py", line 199, in read_text
    blob = functools.reduce(operator.truediv, path.parts, commit.tree)
KeyError: '.cookiecutter.json'
```

**Comment by cjolowicz** [comment]
Is the file checked in? IIRC it needs to be in the repo as of the (last) commit you're importing.

**Comment by mario-bermonti** [comment]
That's probably it. It is not checked in. I created the project from the template a while ago, but I wanted to start using retrocookie to copy some changes back into the template. 

So retrocookie will only work from the commit it is checked in onward, right?

**Comment by cjolowicz** [comment]
Yes. You'll need to reorder the commits so .cookiecutter.json is added before the changes you're interested in, using git rebase -i. Can be a temporary branch that you throw away after importing.

**Comment by mario-bermonti** [comment]
Ok. That seems like a reasonable solution. Thank you!

**Comment by mario-bermonti** [comment]
I am going to close this now.
