### ISSUE TITLE
Incompatibility with pygit2 1.15.0

### ISSUE THREAD

**Issue by bruno-fs** [cjolowicz/retrocookie#758]
Hi, I recently made a fresh installation of retrocookie and found a problem with pygit2.

```Traceback (most recent call last):
  File "/home/bciconel/.local/bin/retrocookie", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/__main__.py", line 120, in main
    retrocookie(
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 162, in retrocookie
    commits = rewrite_commits(
              ^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 87, in rewrite_commits
    return [repository.lookup_replacement(commit) for commit in commits]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 87, in <listcomp>
    return [repository.lookup_replacement(commit) for commit in commits]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/git.py", line 189, in lookup_replacement
    return cast(str, ref.target.hex)
                     ^^^^^^^^^^^^^^
AttributeError: '_pygit2.Oid' object has no attribute 'hex'
```

Manually downgrading `pygit2` fixed the issue here.

**Comment by bruno-fs** [comment]
@cjolowicz would you mind releasing a new version with this fix so it can be fetched properly from pypi?

Thanks in advance!

**Comment by cjolowicz** [comment]
Done
